version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: letsgrind-postgres
    environment:
      POSTGRES_DB: letsgrinddb
      POSTGRES_USER: letsgrinduser
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
